using FinalProjectFruitShopAdmin.Constants;
using FinalProjectFruitShopAdmin.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.Data;
using System.Linq;

namespace FinalProjectFruitShopAdmin.Data
{
    public class UserSQLDbContext : DbContext
    {
        public UserSQLDbContext(DbContextOptions<UserSQLDbContext> options) : base(options) { }

        public DbSet<User> Users { get; set; }
        public DbSet<UserAddress> UserAddresses { get; set; }
        public DbSet<UserPayment> UserPayments { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var roleConverter = new EnumToStringConverter<RoleType>(); // Define converter for Role enum

            modelBuilder.Entity<User>()
                .Property(u => u.Role)
                .HasConversion(roleConverter);

            modelBuilder.Entity<User>()
                .HasKey(a => a.UserId);
            modelBuilder.Entity<UserAddress>()
                .HasKey(a => a.AddressId);
            modelBuilder.Entity<UserPayment>()
                .HasKey(p => p.PaymentId);

            modelBuilder.Entity<UserAddress>()
                .HasOne(a => a.User)
                .WithMany(u => u.Addresses)
                .HasForeignKey(a => a.UserId);

            modelBuilder.Entity<UserPayment>()
                .HasOne(p => p.User)
                .WithMany(u => u.Payments)
                .HasForeignKey(p => p.UserId);

            modelBuilder.Entity<User>()
                .Property(u => u.UserId)
                .ValueGeneratedOnAdd(); // Configure Id to be generated by the database

            modelBuilder.Entity<UserAddress>()
               .Property(a => a.AddressId)
               .ValueGeneratedOnAdd(); // Configure Id to be generated by the database

            modelBuilder.Entity<User>()
                .Property(u => u.DoB)
                .HasColumnType("date");
        }


    }
}
