using FruitsShopBackend.Model;
using Microsoft.EntityFrameworkCore;

namespace FruitsShopBackend.Data
{
    public class UserSQLDbContext : DbContext
    {
        public UserSQLDbContext(DbContextOptions<UserSQLDbContext> options) : base(options) { }

        public DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .Property(u => u.Id)
                .ValueGeneratedOnAdd(); // Configure Id to be generated by the database

            // Additional configurations if needed
        }

    }
}
